### ISSUE TITLE
Use "typed" type formats

### ISSUE THREAD

**Issue by Razican** [vrruiz/xisfits#6]
The `XISFHeader` structure currently uses a `String` to store a Type format. Given that the number of options is a reduced set, it would probably be more convenient to use a Rust `enum` which can also have a `num_bytes()` function that directly returns the number of bytes. This would improve performance a bit, RAM usage a bit, and make the code more maintainable and more clear.

Let me know what you think, and I can implement it.

**Comment by vrruiz** [comment]
I think it could be useful to store the raw value, in case the header is not properly formatted, but yeah why not. Let's go ahead with the enum.
