### ISSUE TITLE
Reduce the cognitive complexity of the `main()` function

### ISSUE THREAD

**Issue by Razican** [vrruiz/xisfits#8]
Currently, the `main()` function has a [cognitive complexity][wiki] of 38, as per `cargo clippy`. This is can carry some problems with optimizations of the compiler, along with making compile times longer and making it more difficult to maintain, as per the [clippy documentation][docs].

I've already seen that the function has some comments indicating various steps of the process, so maybe those could be a great start to divide the code in functions.

Let me know if you need help with this :)

[wiki]: https://en.wikipedia.org/wiki/Cyclomatic_complexity
[docs]: https://rust-lang.github.io/rust-clippy/master/index.html#cognitive_complexity

**Comment by vrruiz** [comment]
I have moved the XISF decoding parts to a new module. cargo clippy doesn't complain anymore.
